// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lock.proto

package cn.nextop.gadget.etcd.grpc.lock;

/**
 * Protobuf type {@code v3lockpb.LockRequest}
 */
@SuppressWarnings("all") public final class LockRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v3lockpb.LockRequest)
    LockRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LockRequest.newBuilder() to construct.
  private LockRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LockRequest() {
    name_ = com.google.protobuf.ByteString.EMPTY;
    lease_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LockRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            name_ = input.readBytes();
            break;
          }
          case 16: {

            lease_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.nextop.gadget.etcd.grpc.lock.JetcdProto.internal_static_v3lockpb_LockRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.nextop.gadget.etcd.grpc.lock.JetcdProto.internal_static_v3lockpb_LockRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.nextop.gadget.etcd.grpc.lock.LockRequest.class, cn.nextop.gadget.etcd.grpc.lock.LockRequest.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString name_;
  /**
   * <pre>
   * name is the identifier for the distributed shared lock to be acquired.
   * </pre>
   *
   * <code>bytes name = 1;</code>
   */
  public com.google.protobuf.ByteString getName() {
    return name_;
  }

  public static final int LEASE_FIELD_NUMBER = 2;
  private long lease_;
  /**
   * <pre>
   * lease is the ID of the lease that will be attached to ownership of the
   * lock. If the lease expires or is revoked and currently holds the lock,
   * the lock is automatically released. Calls to Lock with the same lease will
   * be treated as a single acquistion; locking twice with the same lease is a
   * no-op.
   * </pre>
   *
   * <code>int64 lease = 2;</code>
   */
  public long getLease() {
    return lease_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!name_.isEmpty()) {
      output.writeBytes(1, name_);
    }
    if (lease_ != 0L) {
      output.writeInt64(2, lease_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, name_);
    }
    if (lease_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, lease_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.nextop.gadget.etcd.grpc.lock.LockRequest)) {
      return super.equals(obj);
    }
    cn.nextop.gadget.etcd.grpc.lock.LockRequest other = (cn.nextop.gadget.etcd.grpc.lock.LockRequest) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && (getLease()
        == other.getLease());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LEASE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLease());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.nextop.gadget.etcd.grpc.lock.LockRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v3lockpb.LockRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v3lockpb.LockRequest)
      cn.nextop.gadget.etcd.grpc.lock.LockRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.nextop.gadget.etcd.grpc.lock.JetcdProto.internal_static_v3lockpb_LockRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.nextop.gadget.etcd.grpc.lock.JetcdProto.internal_static_v3lockpb_LockRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.nextop.gadget.etcd.grpc.lock.LockRequest.class, cn.nextop.gadget.etcd.grpc.lock.LockRequest.Builder.class);
    }

    // Construct using cn.nextop.gadget.etcd.grpc.lock.LockRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = com.google.protobuf.ByteString.EMPTY;

      lease_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.nextop.gadget.etcd.grpc.lock.JetcdProto.internal_static_v3lockpb_LockRequest_descriptor;
    }

    public cn.nextop.gadget.etcd.grpc.lock.LockRequest getDefaultInstanceForType() {
      return cn.nextop.gadget.etcd.grpc.lock.LockRequest.getDefaultInstance();
    }

    public cn.nextop.gadget.etcd.grpc.lock.LockRequest build() {
      cn.nextop.gadget.etcd.grpc.lock.LockRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public cn.nextop.gadget.etcd.grpc.lock.LockRequest buildPartial() {
      cn.nextop.gadget.etcd.grpc.lock.LockRequest result = new cn.nextop.gadget.etcd.grpc.lock.LockRequest(this);
      result.name_ = name_;
      result.lease_ = lease_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.nextop.gadget.etcd.grpc.lock.LockRequest) {
        return mergeFrom((cn.nextop.gadget.etcd.grpc.lock.LockRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.nextop.gadget.etcd.grpc.lock.LockRequest other) {
      if (other == cn.nextop.gadget.etcd.grpc.lock.LockRequest.getDefaultInstance()) return this;
      if (other.getName() != com.google.protobuf.ByteString.EMPTY) {
        setName(other.getName());
      }
      if (other.getLease() != 0L) {
        setLease(other.getLease());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.nextop.gadget.etcd.grpc.lock.LockRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.nextop.gadget.etcd.grpc.lock.LockRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString name_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * name is the identifier for the distributed shared lock to be acquired.
     * </pre>
     *
     * <code>bytes name = 1;</code>
     */
    public com.google.protobuf.ByteString getName() {
      return name_;
    }
    /**
     * <pre>
     * name is the identifier for the distributed shared lock to be acquired.
     * </pre>
     *
     * <code>bytes name = 1;</code>
     */
    public Builder setName(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name is the identifier for the distributed shared lock to be acquired.
     * </pre>
     *
     * <code>bytes name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }

    private long lease_ ;
    /**
     * <pre>
     * lease is the ID of the lease that will be attached to ownership of the
     * lock. If the lease expires or is revoked and currently holds the lock,
     * the lock is automatically released. Calls to Lock with the same lease will
     * be treated as a single acquistion; locking twice with the same lease is a
     * no-op.
     * </pre>
     *
     * <code>int64 lease = 2;</code>
     */
    public long getLease() {
      return lease_;
    }
    /**
     * <pre>
     * lease is the ID of the lease that will be attached to ownership of the
     * lock. If the lease expires or is revoked and currently holds the lock,
     * the lock is automatically released. Calls to Lock with the same lease will
     * be treated as a single acquistion; locking twice with the same lease is a
     * no-op.
     * </pre>
     *
     * <code>int64 lease = 2;</code>
     */
    public Builder setLease(long value) {
      
      lease_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * lease is the ID of the lease that will be attached to ownership of the
     * lock. If the lease expires or is revoked and currently holds the lock,
     * the lock is automatically released. Calls to Lock with the same lease will
     * be treated as a single acquistion; locking twice with the same lease is a
     * no-op.
     * </pre>
     *
     * <code>int64 lease = 2;</code>
     */
    public Builder clearLease() {
      
      lease_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v3lockpb.LockRequest)
  }

  // @@protoc_insertion_point(class_scope:v3lockpb.LockRequest)
  private static final cn.nextop.gadget.etcd.grpc.lock.LockRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.nextop.gadget.etcd.grpc.lock.LockRequest();
  }

  public static cn.nextop.gadget.etcd.grpc.lock.LockRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LockRequest>
      PARSER = new com.google.protobuf.AbstractParser<LockRequest>() {
    public LockRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LockRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LockRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LockRequest> getParserForType() {
    return PARSER;
  }

  public cn.nextop.gadget.etcd.grpc.lock.LockRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

