// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lock.proto

package cn.nextop.gadget.etcd.grpc.lock;

public interface UnlockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v3lockpb.UnlockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * key is the lock ownership key granted by Lock.
   * </pre>
   *
   * <code>bytes key = 1;</code>
   */
  com.google.protobuf.ByteString getKey();
}
