// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.nextop.gadget.etcd.grpc;

public interface AuthRoleGetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.AuthRoleGetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>repeated .authpb.Permission perm = 2;</code>
   */
  java.util.List<cn.nextop.gadget.etcd.grpc.Permission> 
      getPermList();
  /**
   * <code>repeated .authpb.Permission perm = 2;</code>
   */
  cn.nextop.gadget.etcd.grpc.Permission getPerm(int index);
  /**
   * <code>repeated .authpb.Permission perm = 2;</code>
   */
  int getPermCount();
  /**
   * <code>repeated .authpb.Permission perm = 2;</code>
   */
  java.util.List<? extends cn.nextop.gadget.etcd.grpc.PermissionOrBuilder> 
      getPermOrBuilderList();
  /**
   * <code>repeated .authpb.Permission perm = 2;</code>
   */
  cn.nextop.gadget.etcd.grpc.PermissionOrBuilder getPermOrBuilder(
      int index);
}
