// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.nextop.gadget.etcd.grpc;

public interface DeleteRangeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.DeleteRangeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * deleted is the number of keys deleted by the delete range request.
   * </pre>
   *
   * <code>int64 deleted = 2;</code>
   */
  long getDeleted();

  /**
   * <pre>
   * if prev_kv is set in the request, the previous key-value pairs will be returned.
   * </pre>
   *
   * <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
   */
  java.util.List<cn.nextop.gadget.etcd.grpc.KeyValue> 
      getPrevKvsList();
  /**
   * <pre>
   * if prev_kv is set in the request, the previous key-value pairs will be returned.
   * </pre>
   *
   * <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
   */
  cn.nextop.gadget.etcd.grpc.KeyValue getPrevKvs(int index);
  /**
   * <pre>
   * if prev_kv is set in the request, the previous key-value pairs will be returned.
   * </pre>
   *
   * <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
   */
  int getPrevKvsCount();
  /**
   * <pre>
   * if prev_kv is set in the request, the previous key-value pairs will be returned.
   * </pre>
   *
   * <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
   */
  java.util.List<? extends cn.nextop.gadget.etcd.grpc.KeyValueOrBuilder> 
      getPrevKvsOrBuilderList();
  /**
   * <pre>
   * if prev_kv is set in the request, the previous key-value pairs will be returned.
   * </pre>
   *
   * <code>repeated .mvccpb.KeyValue prev_kvs = 3;</code>
   */
  cn.nextop.gadget.etcd.grpc.KeyValueOrBuilder getPrevKvsOrBuilder(
      int index);
}
