// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.nextop.gadget.etcd.grpc;

public interface HashKVRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.HashKVRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * revision is the key-value store revision for the hash operation.
   * </pre>
   *
   * <code>int64 revision = 1;</code>
   */
  long getRevision();
}
