// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.nextop.gadget.etcd.grpc;

public interface HashRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.HashRequest)
    com.google.protobuf.MessageOrBuilder {
}
