// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.nextop.gadget.etcd.grpc;

public interface MemberAddResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.MemberAddResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * member is the member information for the added member.
   * </pre>
   *
   * <code>.etcdserverpb.Member member = 2;</code>
   */
  boolean hasMember();
  /**
   * <pre>
   * member is the member information for the added member.
   * </pre>
   *
   * <code>.etcdserverpb.Member member = 2;</code>
   */
  cn.nextop.gadget.etcd.grpc.Member getMember();
  /**
   * <pre>
   * member is the member information for the added member.
   * </pre>
   *
   * <code>.etcdserverpb.Member member = 2;</code>
   */
  cn.nextop.gadget.etcd.grpc.MemberOrBuilder getMemberOrBuilder();

  /**
   * <pre>
   * members is a list of all members after adding the new member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 3;</code>
   */
  java.util.List<cn.nextop.gadget.etcd.grpc.Member> 
      getMembersList();
  /**
   * <pre>
   * members is a list of all members after adding the new member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 3;</code>
   */
  cn.nextop.gadget.etcd.grpc.Member getMembers(int index);
  /**
   * <pre>
   * members is a list of all members after adding the new member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 3;</code>
   */
  int getMembersCount();
  /**
   * <pre>
   * members is a list of all members after adding the new member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 3;</code>
   */
  java.util.List<? extends cn.nextop.gadget.etcd.grpc.MemberOrBuilder> 
      getMembersOrBuilderList();
  /**
   * <pre>
   * members is a list of all members after adding the new member.
   * </pre>
   *
   * <code>repeated .etcdserverpb.Member members = 3;</code>
   */
  cn.nextop.gadget.etcd.grpc.MemberOrBuilder getMembersOrBuilder(
      int index);
}
