// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.nextop.gadget.etcd.grpc;

public interface PutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.PutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * if prev_kv is set in the request, the previous key-value pair will be returned.
   * </pre>
   *
   * <code>.mvccpb.KeyValue prev_kv = 2;</code>
   */
  boolean hasPrevKv();
  /**
   * <pre>
   * if prev_kv is set in the request, the previous key-value pair will be returned.
   * </pre>
   *
   * <code>.mvccpb.KeyValue prev_kv = 2;</code>
   */
  cn.nextop.gadget.etcd.grpc.KeyValue getPrevKv();
  /**
   * <pre>
   * if prev_kv is set in the request, the previous key-value pair will be returned.
   * </pre>
   *
   * <code>.mvccpb.KeyValue prev_kv = 2;</code>
   */
  cn.nextop.gadget.etcd.grpc.KeyValueOrBuilder getPrevKvOrBuilder();
}
