// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.nextop.gadget.etcd.grpc;

public interface TxnResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.TxnResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseHeader getHeader();
  /**
   * <code>.etcdserverpb.ResponseHeader header = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * succeeded is set to true if the compare evaluated to true or false otherwise.
   * </pre>
   *
   * <code>bool succeeded = 2;</code>
   */
  boolean getSucceeded();

  /**
   * <pre>
   * responses is a list of responses corresponding to the results from applying
   * success if succeeded is true or failure if succeeded is false.
   * </pre>
   *
   * <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
   */
  java.util.List<cn.nextop.gadget.etcd.grpc.ResponseOp> 
      getResponsesList();
  /**
   * <pre>
   * responses is a list of responses corresponding to the results from applying
   * success if succeeded is true or failure if succeeded is false.
   * </pre>
   *
   * <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseOp getResponses(int index);
  /**
   * <pre>
   * responses is a list of responses corresponding to the results from applying
   * success if succeeded is true or failure if succeeded is false.
   * </pre>
   *
   * <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
   */
  int getResponsesCount();
  /**
   * <pre>
   * responses is a list of responses corresponding to the results from applying
   * success if succeeded is true or failure if succeeded is false.
   * </pre>
   *
   * <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
   */
  java.util.List<? extends cn.nextop.gadget.etcd.grpc.ResponseOpOrBuilder> 
      getResponsesOrBuilderList();
  /**
   * <pre>
   * responses is a list of responses corresponding to the results from applying
   * success if succeeded is true or failure if succeeded is false.
   * </pre>
   *
   * <code>repeated .etcdserverpb.ResponseOp responses = 3;</code>
   */
  cn.nextop.gadget.etcd.grpc.ResponseOpOrBuilder getResponsesOrBuilder(
      int index);
}
