// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package cn.nextop.gadget.etcd.grpc;

public interface WatchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.WatchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.etcdserverpb.WatchCreateRequest create_request = 1;</code>
   */
  boolean hasCreateRequest();
  /**
   * <code>.etcdserverpb.WatchCreateRequest create_request = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.WatchCreateRequest getCreateRequest();
  /**
   * <code>.etcdserverpb.WatchCreateRequest create_request = 1;</code>
   */
  cn.nextop.gadget.etcd.grpc.WatchCreateRequestOrBuilder getCreateRequestOrBuilder();

  /**
   * <code>.etcdserverpb.WatchCancelRequest cancel_request = 2;</code>
   */
  boolean hasCancelRequest();
  /**
   * <code>.etcdserverpb.WatchCancelRequest cancel_request = 2;</code>
   */
  cn.nextop.gadget.etcd.grpc.WatchCancelRequest getCancelRequest();
  /**
   * <code>.etcdserverpb.WatchCancelRequest cancel_request = 2;</code>
   */
  cn.nextop.gadget.etcd.grpc.WatchCancelRequestOrBuilder getCancelRequestOrBuilder();

  public cn.nextop.gadget.etcd.grpc.WatchRequest.RequestUnionCase getRequestUnionCase();
}
